### ISSUE TITLE
It does not detect any edge if we are in sunlight

### ISSUE THREAD

**Issue by JeetSA** [hannesa2/LiveEdgeDetection#107]
Is there a way to detect the edge when we are in bright light? Right now I am not able to do that in this demo.

Can anyone please help me with this?

Thanks in advance.

**Comment by hannesa2** [comment]
This is a more advanced task handling less contrast.
If you have some progress, please share it with us

**Comment by SiavashB** [comment]
Hi, I'm also finding that this lib will not work in the real world because it only works in perfect conditions with a solid color dark background. But I have a suggestion.

The lib does not need to perfectly detect corners because the user is given the opportunity to adjust the corners before the scan is made. So if you just reduce the threshold of what is consider acceptable conditions to take the picture, then you will work in more conditions; yes there will be more errors, but user can always adjust the corners manually and thats better than not being able to take a picture at all.

**Comment by hannesa2** [comment]
Maybe a configurable threshold is a way to go ?
I'm happy to approve any pull request
